name: TownyExternal
version: '2026.2.1'
main: site.remlit.townyexternal.TownyExternal
paper-plugin-loader: site.remlit.townyexternal.TownyExternalPluginLoader
api-version: '1.20'
authors: [ blueb ]
depend: [ Towny ]
